### PR TITLE
feat(doc): Add new post for ffmpeg wasm. Refs #20.

### PR DESCRIPTION
**Pull request by ducto**
Uchida-san,

Can you please review the new post which I created for ffmpeg wasm.

Thank you and I look forward to hearing feedback from you

### CODE REVIEW

**Comment by shishimaru** [comment]
Duc-san

Thank you for creating ! I will review later.

**Comment by shishimaru** [comment]
@ducto 
I reviewed the post and put some feedback on the document with TODO keywords. Please check.
Basically, the post is less informative and please add more detail to attract the readers.

**Comment by ducto** [comment]
@shishimaru Uchida-san,

Thank you for your kind review. Allow me to check and update it as advised.

Yours sincerely

**Comment by ducto** [comment]
@shishimaru Uchida-san,

I am sorry for the delay, I just updated the article based on your review. Can you please check?

Thank you

**Pull request merged**
